version: '3'
services:
  # app server
  app:
    build: app/build
    image: mana/springbootsec-app
    ports:
      - "8080:8080"
    links:
      - "db:db"
    command:
      sh -c "(cd app; ./gradlew run)"
    environment:
      # mysqlの接続設定 host:portはコンテナ名指定
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://db:3306/test_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      spring.datasource.username: "docker"
      spring.datasource.password: "pass"
  # db server ( mysql )
  db:
    build: .
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: pass
      TZ: UTC
    healthcheck:
          test: ["CMD", "mysql", "-h", "localhost", "-P", "3306", "-u", "root", "--password=pass", "-e", "select 1", "test_db"]
          interval: 1s
          timeout: 3s
          retries: 30
